output_dir: outputs/GPT-tiny
tokenizer_encoding: gpt2
model_config:
  n_embd: 512
  n_head: 4
  n_positions: 128
  n_layer: 4
device: auto
batch_size: 32
seq_len: 128
num_warmup_steps: 10
num_training_steps: 1000
grad_accumulation_steps: 1
min_lr: 5.0e-05
max_lr: 0.0005
